<?php


namespace Product\Models;
use Illuminate\Database\Eloquent\Model;

class ProductMeta extends Model
{
    protected $table = 'product_meta';
    protected $fillable = ['product_id','enable_color','colors','enable_size','size'];


    protected $casts = [
        'colors'      => 'array',
        'size'        => 'array'
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ( $this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }
}
