<?php


namespace Faq\Providers;


use Illuminate\Support\ServiceProvider;
use Faq\Hook\FaqHook;

class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[FaqHook::class,'handle'],10);
    }
}
